### ISSUE TITLE
안녕하세요 설치 관련 문의입니다.

### ISSUE THREAD

**Issue by iam1492** [i0seph/textsearch_ko#1]
연락드릴 방법이 없어서 요기에 문의드립니다.

postgresql 로 full text search 를 해보고 싶어서 시도중인데요.

현재 제 mac 로컬에 mecab 과 dic 은 설치한 상태인데 

include path 와 lib path 를 설정을 하고 build.sh 를 하면 

계속해서  

sudo -u postgres psql -f ts_mecab_ko.sql [제 디비] 

를 하면 

could not access file "$libdir/ts_mecab_ko": No such file or directory

라고 나옵니다. 실제 해당 폴더에는 ts_mecab.ko.so 파일은 있는데 왠지 libdir/ts_mecab_ko 파일은 제 시스템에 존재하지 않는 느낌입니다.

find 로 라이브러리 파일을 찾아보니

kaiui-MacBook-Pro:textsearch_ko kaimacbook$ sudo find / -name 'ts_mecab_ko*'
/Users/kaimacbook/src/textsearch_ko/ts_mecab_ko.c
/Users/kaimacbook/src/textsearch_ko/ts_mecab_ko.h
/Users/kaimacbook/src/textsearch_ko/ts_mecab_ko.o
/Users/kaimacbook/src/textsearch_ko/ts_mecab_ko.so
/Users/kaimacbook/src/textsearch_ko/ts_mecab_ko.sql
/usr/local/Cellar/postgresql/9.3.5_1/lib/ts_mecab_ko.so
/usr/local/Cellar/postgresql/9.3.5_1/share/postgresql/contrib/ts_mecab_ko.sql

이렇게만 나오고 있습니다.

혹시 좋은 제가 어떤것을 잘못하고 있을까 조언을 구할 수 있을지요?

**Comment by i0seph** [comment]
답변이 늦어 죄송합니다. 

맥환경에서는 안해봐서 잘은 모르지만, 
일단 동적으로 

psql 안에서 

load /usr/local/Cellar/postgresql/9.3.5_1/lib/ts_mecab_ko(또는.so)

명령으로 해당 라이브러리를 불러올 수 있는지부터 확인해보십시오.

잘 로딩이 된다면, $libdir 값이 초기 설치할 때의 값과 달라진 것 같습니다. 
이런 경우는 그냥 postgresql.conf에 절대경로로 적어주면 됩니다. 

그렇지 않고, 해당 라이브러리가 로딩하는데 필요한 부가 라이브러리를 못 찾아서 로딩을 못한다면, 
ts_mecab_ko.so 파일이 로딩하는 데 필요한 기타 다른 라이브러리를 찾아서 그들이 로딩 될 수 있도록
LD_LIBRARY_PATH 값을 조정해 주어야 할 것 같습니다. 

부디 성공하시길.

**Comment by iam1492** [comment]
넵 자세한 설명 감사합니다.

시간날때 한번 시도해보고 메일 드릴께요^^

안드로이드 개발자라 서버는 영잼병입니다.

좋은 프로젝트감사드려요ㅎㅎ
2015. 5. 12. 오후 5:38에 "Ioseph Kim" notifications@github.com님이 작성:

**Comment by iam1492** [comment]
안녕하세요 한가지만 추가로 질문 드릴수있을까요?

혹시 테스트 해보신 서버환경이 어떻게 되시나요?

제가 로컬은 맥인데 실제 적용하고 싶은 서버는 ubuntu 12 입니다. 혹시 실서버에서는 문제 없이 될까해서요~

그리고 build.sh 보면

/data/mecab-ko/include

/data/mecab-ko/lib

폴더를 명시해 두셨는데 이건 mecab 설치시에 뭔가 따로 path를 지정해주신건가요?

감사합니다.

2015년 5월 12일 오후 9:48, 정우람 chickenwooduri@gmail.com님이 작성:
