### ISSUE TITLE
형태소 분석 오류가 납니다.

### ISSUE THREAD

**Issue by ParkKM** [i0seph/textsearch_ko#3]
'알려드립니다.'
위 문구에 대한 형태소분석이 에러가 발생해서 문의 드립니다.

mecab 라이브러리 자체에서 실행시에는
mecab -d /usr/local/lib/mecab/dic/mecab-ko-dic
알려드립니다.
알려  VV+EC,_,F,알려,Inflect,VV,EC,알리/VV/_+어/EC/*
드립니다    VX+EF,_,F,드립니다,Inflect,VX,EF,드리/VX/_+ᄇ니다/EF/*
.   SF,_,_,_,_,_,_,*
EOS

위와 같이 형태소 분석이 잘 되지만

textsearch_ko 설치 후 쿼리로 실행시
select \* from mecabko_analyze('알려드립니다.');
ERROR:  XX000: invalid memory alloc request size 1321177542
LOCATION:  palloc, mcxt.c:664
Time: 2.673 ms

위와 같은 오류가 발생합니다.

그에따라 to_tsvector 도 에러가 나구요.

원인분석 요청드려도 될까요?

**Comment by ParkKM** [comment]
참고로 환경은
RHEL 6 64비트
9.4.4.9 버전 입니다.

**Comment by i0seph** [comment]
출장 중이여서 주말에 살펴볼게요

**Comment by ParkKM** [comment]
mecab-ko-dic 1.6.1 설치시는 에러가 발생하지 않네요.
최신버전(2.1.x) 을 설치하면 에러가 발생합니다.  최신버전 사전과의 문제인 듯 합니다.

참고하세요. ^^
