### ISSUE TITLE
궁금한점이 있어 질문드려요

### ISSUE THREAD

**Issue by sageboy76** [i0seph/textsearch_ko#5]
postgresql에서 한글 검색을 구현해보고 싶어서 설치하고 검색을 해보고 있는데
아래와 같은경우는 어떻게 처리를 해야 하는지 궁금합니다.

예제)
내용 : 삼성전자 실적이 많이 개선되었다.
검색어 : 삼성 or 삼성전자

이런경우 형태소가 '개선':4 '많이':3 '삼성전자':1 '실적':2 이런식으로 나누어져서

'삼성'으로 검색할경우 나오지가 않는데 '삼성'으로 검색했을경우나 '삼성전자'로

검색했을경우 모두 나올수 있게 하는 방법이 있는지요 ?

일반적인 검색이라면 '삼성'과  '삼성전자"로 검색할경우 모두 나오는게 맞다고 생각이 들거든요

그래서 '삼성'을 사용자사전에 등록해보니 삼성전자로 검색이 되지 않습니다.

mecab에서 보니 삼성+전자 합성어로 나오긴 하는데 그부분을 잘 처리하면 될꺼 같은데

C를 할줄 몰라서 어찌해야 할지 모르고 있습니다.

도움 주셨으면 합니다.

**Comment by i0seph** [comment]
해당 문제를 풀려면, 복합 명사 처리를 개선해야하는데, 
일단, 
```text
ioseph=> select * from mecabko_analyze('삼성전자');
   word   | type | part1st | partlast | pronounce | conjtype | conjugation | basic |        detail         |  lucene  
----------+------+---------+----------+-----------+----------+-------------+-------+-----------------------+----------
 삼성전자 | NNP  |         | F        | 삼성전자  | Compound |             |       | 삼성/NNG/*+전자/NNG/* | 삼성전자
(1개 행)
```

형태로 mecab 에서 반환하는 구조로는 conjtype (연결종류)와 detail(세부분석) 로 복합어인 경우를 처리하는 작업을 더 해야합니다. 현재 모듈은 Inflect (용언 활용)에 대해서는 그 용언의 어근만 처리하는 기능을 추가했는데, 복합어인 경우는 처리하지 않았습니다. 

윗 경우라면, 
'개선':4 '많이':3 '삼성전자':1 '실적':2 
이 결과를 
'개선':5 '많이':4 '실적':3 '삼성':1 '전자':2 
이렇게 중복처리해야 원하는 결과가 나올 것 같습니다.

아직까지는 개선 계획이 없습니다.  긴 여름 휴가가 있으면 그 때 심심하면 한 번 도전해 보겠습니다.
